name: flutter_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  web_socket_channel: ^3.0.3
  fluttertoast: ^8.2.4
  isolate: ^2.1.1
  intl: ^0.20.2
  provider: ^6.1.1
  audio_streamer: ^4.1.1
  device_info_plus: ^11.4.0
  share_plus: ^11.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

